name: "Owners check"
description: "List reviewer for all changed files"
inputs:
  auto-add-reviewers:
    description: "Should the reviewers be automatically added to the PR?"
    required: false
  token:
    description: "Github token"
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
